# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelApp' do

pod 'Moya', '~> 12.0'
  target 'MarvelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAppUITests' do
    # Pods for testing
  end

end
